export default [
  {
    title: 'Oak Harbor Soccer',
    subHeader: 'Full Stack Application',
    avatarSrc: 'https://res.cloudinary.com/dpka4vhu6/image/upload/v1528998284/amwebdev/oakharborsoccerlogo.png',
    screenshot: 'https://res.cloudinary.com/dpka4vhu6/image/upload/v1528924595/amwebdev/ohsPreview.png',
    description: 'I was contracted by the Oak Harbor School District to create a website application that allowed users to keep track of rosters, player stats, and more.',
    skills: [
      'Express',
      'NodeJS',
      'Angular',
      'Mongoose',
      'MongoDB',
    ],
    url: 'https://www.oakharborsoccer.com',
  },
  {
    title: 'Cuz Septic',
    subHeader: 'Serverless Gatsby Site',
    avatarSrc: 'https://res.cloudinary.com/dpka4vhu6/image/upload/v1571515552/amwebdev/cuz-septic-logo.png',
    screenshot: 'https://res.cloudinary.com/dpka4vhu6/image/upload/v1571515613/amwebdev/cuz-septic-screenshot.png',
    description: 'A website for a local plumbing business, which helps to boost their online presence and SEO ratings in order to generate more leads.',
    skills: [
      'Gatsby',
      'React',
      'Netlify',
    ],
    url: 'https://distracted-heisenberg-c2b056.netlify.com',
  },
  {
    title: 'Rock On 3v3',
    subHeader: 'Full Stack Application',
    avatarSrc: 'https://res.cloudinary.com/dpka4vhu6/image/upload/v1528924588/amwebdev/RockOn2018Logo.png',
    screenshot: 'https://res.cloudinary.com/dpka4vhu6/image/upload/v1528924584/amwebdev/rockOnPreview.jpg',
    description: 'This project involved creating an online portal for teams to register for a local soccer tournament, as well as view tournament brackets. ',
    skills: [
      'Express',
      'NodeJS',
      'Angular',
      'Mongoose',
      'MongoDB',
      'Stripe',
    ],
    url: 'https://www.rockon3v3.com',
  },
  {
    title: 'Melnick & Son\'s Painting Business',
    subHeader: 'Wordpress Site',
    avatarSrc: 'https://res.cloudinary.com/dpka4vhu6/image/upload/v1528997638/amwebdev/logo.jpg',
    screenshot: 'https://res.cloudinary.com/dpka4vhu6/image/upload/v1528924596/amwebdev/mandsPreview.png',
    description: 'A website for a local painting business, which helps to boost their online presence and SEO ratings in order to generate more leads.',
    skills: [
      'Wordpress',
    ],
    url: 'https://www.melnickandsons.com',
  },
  {
    title: 'Sunset Valley Pony Club',
    subHeader: 'Wordpress Ecommerce website',
    avatarSrc: 'https://res.cloudinary.com/dpka4vhu6/image/upload/v1571442057/amwebdev/logo.png',
    screenshot: 'https://res.cloudinary.com/dpka4vhu6/image/upload/v1528999185/amwebdev/svpcSitePreview.jpg',
    description: 'The Sunset Valley Pony Club website was designed to help the organization to organize events, sell tickets and maintain a blog for its members.',
    skills: [
      'Wordpress',
      'Woocommerce',
    ],
    url: 'https://www.sunsetvalleyponyclub.com',
  },
];
